#!/bin/bash
echo "═══════════════════════════════════════════════════════════════"
echo "📦 React 18 Compatibility Verification"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Core React packages:"
pnpm list react react-dom @types/react @types/react-dom --depth=0 2>/dev/null | grep -E "(react|react-dom)" | grep -v "WARN"
echo ""
echo "Build tools:"
pnpm list vite @vitejs/plugin-react gh-pages --depth=0 2>/dev/null | grep -E "(vite|plugin-react|gh-pages)" | grep -v "WARN"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ All packages are React 18 compatible!"
echo "═══════════════════════════════════════════════════════════════"
